import type { Achievement } from '@/types/challenge';

/**
 * Achievement definitions — unlocked based on user milestones.
 * Checked automatically after each workout completion.
 * 22 achievements across common, rare, epic, and legendary tiers.
 */
export const ACHIEVEMENTS: Achievement[] = [
  // ===== COMMON (Easy to unlock) =====
  {
    id: 'ach-first-workout',
    name: 'First Step',
    description: 'Complete your very first workout session.',
    icon: 'Footprints',
    condition: { type: 'total_workouts', value: 1 },
    pointsReward: 50,
    rarity: 'common',
  },
  {
    id: 'ach-five-workouts',
    name: 'Getting Started',
    description: 'Complete 5 workout sessions.',
    icon: 'TrendingUp',
    condition: { type: 'total_workouts', value: 5 },
    pointsReward: 100,
    rarity: 'common',
  },
  {
    id: 'ach-100-points',
    name: 'Point Collector',
    description: 'Earn a total of 100 points.',
    icon: 'Star',
    condition: { type: 'total_points', value: 100 },
    pointsReward: 25,
    rarity: 'common',
  },
  {
    id: 'ach-3-day-streak',
    name: 'Hat Trick',
    description: 'Maintain a 3-day workout streak.',
    icon: 'Flame',
    condition: { type: 'streak', value: 3 },
    pointsReward: 75,
    rarity: 'common',
  },
  {
    id: 'ach-500-calories',
    name: 'Calorie Crusher',
    description: 'Burn a total of 500 calories across all workouts.',
    icon: 'Zap',
    condition: { type: 'total_calories', value: 500 },
    pointsReward: 50,
    rarity: 'common',
  },
  {
    id: 'ach-60-minutes',
    name: 'One Hour Strong',
    description: 'Accumulate 60 total minutes of workout time.',
    icon: 'Clock',
    condition: { type: 'total_minutes', value: 60 },
    pointsReward: 50,
    rarity: 'common',
  },
  {
    id: 'ach-first-challenge',
    name: 'Challenger',
    description: 'Complete your first challenge.',
    icon: 'Target',
    condition: { type: 'challenges_completed', value: 1 },
    pointsReward: 100,
    rarity: 'common',
  },

  // ===== RARE (Moderate effort) =====
  {
    id: 'ach-10-workouts',
    name: 'Dedicated',
    description: 'Complete 10 workout sessions.',
    icon: 'Dumbbell',
    condition: { type: 'total_workouts', value: 10 },
    pointsReward: 200,
    rarity: 'rare',
  },
  {
    id: 'ach-1000-points',
    name: 'Thousand Club',
    description: 'Earn a total of 1,000 points.',
    icon: 'Crown',
    condition: { type: 'total_points', value: 1000 },
    pointsReward: 150,
    rarity: 'rare',
  },
  {
    id: 'ach-7-day-streak',
    name: 'Week Warrior',
    description: 'Maintain a 7-day workout streak.',
    icon: 'Flame',
    condition: { type: 'streak', value: 7 },
    pointsReward: 200,
    rarity: 'rare',
  },
  {
    id: 'ach-5000-calories',
    name: 'Furnace',
    description: 'Burn a total of 5,000 calories.',
    icon: 'Zap',
    condition: { type: 'total_calories', value: 5000 },
    pointsReward: 200,
    rarity: 'rare',
  },
  {
    id: 'ach-500-minutes',
    name: 'Half Day Strong',
    description: 'Accumulate 500 total minutes of workout time.',
    icon: 'Clock',
    condition: { type: 'total_minutes', value: 500 },
    pointsReward: 200,
    rarity: 'rare',
  },
  {
    id: 'ach-custom-workout',
    name: 'Creator',
    description: 'Create your first custom workout plan.',
    icon: 'Pencil',
    condition: { type: 'custom_workouts_created', value: 1 },
    pointsReward: 150,
    rarity: 'rare',
  },
  {
    id: 'ach-body-logged',
    name: 'Self Tracker',
    description: 'Log your body weight 3 times.',
    icon: 'Scale',
    condition: { type: 'body_weight_logged', value: 3 },
    pointsReward: 100,
    rarity: 'rare',
  },
  {
    id: 'ach-3-challenges',
    name: 'Challenge Hunter',
    description: 'Complete 3 challenges.',
    icon: 'Target',
    condition: { type: 'challenges_completed', value: 3 },
    pointsReward: 250,
    rarity: 'rare',
  },

  // ===== EPIC (Significant commitment) =====
  {
    id: 'ach-25-workouts',
    name: 'Iron Will',
    description: 'Complete 25 workout sessions.',
    icon: 'Shield',
    condition: { type: 'total_workouts', value: 25 },
    pointsReward: 400,
    rarity: 'epic',
  },
  {
    id: 'ach-5000-points',
    name: 'Elite Earner',
    description: 'Earn a total of 5,000 points.',
    icon: 'Crown',
    condition: { type: 'total_points', value: 5000 },
    pointsReward: 350,
    rarity: 'epic',
  },
  {
    id: 'ach-14-day-streak',
    name: 'Unstoppable',
    description: 'Maintain a 14-day workout streak.',
    icon: 'Flame',
    condition: { type: 'streak', value: 14 },
    pointsReward: 400,
    rarity: 'epic',
  },
  {
    id: 'ach-30-day-streak',
    name: 'Month of Iron',
    description: 'Maintain a 30-day workout streak.',
    icon: 'Award',
    condition: { type: 'streak', value: 30 },
    pointsReward: 600,
    rarity: 'epic',
  },
  {
    id: 'ach-50-workouts',
    name: 'Half Century',
    description: 'Complete 50 workout sessions.',
    icon: 'Trophy',
    condition: { type: 'total_workouts', value: 50 },
    pointsReward: 600,
    rarity: 'epic',
  },
  {
    id: 'ach-every-weekday',
    name: 'Full Week Coverage',
    description: 'Complete at least one workout on every day of the week (Mon-Sun).',
    icon: 'Calendar',
    condition: { type: 'workout_on_each_weekday', value: 7 },
    pointsReward: 500,
    rarity: 'epic',
  },

  // ===== LEGENDARY (Extreme dedication) =====
  {
    id: 'ach-100-workouts',
    name: 'Centurion',
    description: 'Complete 100 workout sessions. You are a fitness legend.',
    icon: 'Trophy',
    condition: { type: 'total_workouts', value: 100 },
    pointsReward: 1500,
    rarity: 'legendary',
  },
  {
    id: 'ach-50000-calories',
    name: 'Human Furnace',
    description: 'Burn a total of 50,000 calories. That\'s over 14 pounds of fat equivalent!',
    icon: 'Zap',
    condition: { type: 'total_calories', value: 50000 },
    pointsReward: 1200,
    rarity: 'legendary',
  },
  {
    id: 'ach-10000-minutes',
    description: 'Accumulate 10,000 total minutes — that\'s nearly 7 full days of exercise.',
    name: 'Time Immortal',
    icon: 'Clock',
    condition: { type: 'total_minutes', value: 10000 },
    pointsReward: 1000,
    rarity: 'legendary',
  },
  {
    id: 'ach-longest-streak-30',
    name: 'Never Break the Chain',
    description: 'Achieve a longest streak of 30 days at any point.',
    icon: 'Link',
    condition: { type: 'longest_streak', value: 30 },
    pointsReward: 800,
    rarity: 'legendary',
  },
];

/* ===== Rarity Configuration ===== */
export const RARITY_CONFIG = {
  common: {
    label: 'Common',
    color: '#8A807A',
    bgColor: 'rgba(138, 128, 122, 0.1)',
    iconSize: 20,
  },
  rare: {
    label: 'Rare',
    color: '#7BA7CC',
    bgColor: 'rgba(123, 167, 204, 0.15)',
    iconSize: 22,
  },
  epic: {
    label: 'Epic',
    color: '#E8A87C',
    bgColor: 'rgba(232, 168, 124, 0.15)',
    iconSize: 24,
  },
  legendary: {
    label: 'Legendary',
    color: '#D4756B',
    bgColor: 'rgba(212, 117, 107, 0.15)',
    iconSize: 26,
  },
} as const;

export type Rarity = keyof typeof RARITY_CONFIG;
