import type { Challenge } from '@/types/challenge';
import { ChallengeType } from '@/types/common';

/**
 * Pre-built fitness challenges.
 * Users can start these to add gamification to their fitness journey.
 * All data is free and locally defined.
 */
export const CHALLENGES: Challenge[] = [
  {
    id: 'challenge-30day-plank',
    name: '30-Day Plank Challenge',
    description: 'Gradually increase your plank hold time over 30 days. Start at 20 seconds, finish at 5 minutes!',
    type: ChallengeType.DAILY,
    targetValue: 1500, // 25 minutes total accumulated
    unit: 'seconds',
    durationDays: 30,
    dailyTarget: 50, // start ~20s, scale up, average ~50s/day
    pointsReward: 500,
    icon: 'Shield',
    color: 'blue',
    difficulty: 'medium',
    instructions: [
      'Day 1-5: Hold plank for 20-30 seconds',
      'Day 6-10: Hold for 40-60 seconds',
      'Day 11-15: Hold for 60-90 seconds',
      'Day 16-20: Hold for 90-120 seconds',
      'Day 21-25: Hold for 120-180 seconds',
      'Day 26-30: Hold for 180-300 seconds',
      'Rest days are allowed but will break your streak',
    ],
  },
  {
    id: 'challenge-100-pushups',
    name: '100 Push-Ups Daily',
    description: 'Complete 100 push-ups every day for 14 days. Break them into sets as needed.',
    type: ChallengeType.DAILY,
    targetValue: 1400,
    unit: 'reps',
    durationDays: 14,
    dailyTarget: 100,
    pointsReward: 600,
    icon: 'Target',
    color: 'peach',
    difficulty: 'hard',
    instructions: [
      'Complete 100 total push-ups per day',
      'Break into sets: 10 sets of 10, 5 sets of 20, etc.',
      'Any push-up variation counts (knee, standard, wide)',
      'Rest between sets as needed',
      'Track your total reps each day',
    ],
  },
  {
    id: 'challenge-50km-run',
    name: 'Run 50km in a Month',
    description: 'Accumulate 50 kilometers of running over 30 days. That\'s about 1.6km per day on average.',
    type: ChallengeType.DISTANCE,
    targetValue: 50,
    unit: 'km',
    durationDays: 30,
    dailyTarget: 1.7,
    pointsReward: 800,
    icon: 'MapPin',
    color: 'green',
    difficulty: 'medium',
    instructions: [
      'Log all running distances in your workout diary',
      'Any running pace counts',
      'Treadmill running also counts',
      'Spread the distance across the month — no need to run daily',
      'Aim for 3-4 running sessions per week',
    ],
  },
  {
    id: 'challenge-yoga-morning',
    name: 'Morning Yoga Streak',
    description: 'Practice yoga or stretching every morning for 21 days to build a healthy habit.',
    type: ChallengeType.STREAK,
    targetValue: 21,
    unit: 'days',
    durationDays: 21,
    dailyTarget: 10, // at least 10 minutes
    pointsReward: 450,
    icon: 'Sun',
    color: 'green',
    difficulty: 'easy',
    instructions: [
      'Complete at least 10 minutes of yoga or stretching each morning',
      'Any style counts: Hatha, Vinyasa, or general stretching',
      'Must be done before noon to count',
      'Log it as a completed workout session',
      'Focus on consistency, not intensity',
    ],
  },
  {
    id: 'challenge-10000-steps',
    name: '10,000 Steps Daily',
    description: 'Hit 10,000 steps every day for 14 days. Walking is the most underrated exercise!',
    type: ChallengeType.DAILY,
    targetValue: 140000,
    unit: 'steps',
    durationDays: 14,
    dailyTarget: 10000,
    pointsReward: 500,
    icon: 'Footprints',
    color: 'blue',
    difficulty: 'medium',
    instructions: [
      'Walk at least 10,000 steps every day',
      'All walking counts: commuting, errands, exercise',
      'Use your phone\'s step counter or manually log',
      'Take the stairs, park farther away, walk after meals',
      'Log your steps in the activity tracker',
    ],
  },
  {
    id: 'challenge-200-squats',
    name: '200 Squats Challenge',
    description: 'Work up to 200 squats in a single session over 30 days. Progressive overload for your legs.',
    type: ChallengeType.REPETITION,
    targetValue: 200,
    unit: 'reps',
    durationDays: 30,
    dailyTarget: undefined, // not daily — it's a progressive single-session goal
    pointsReward: 550,
    icon: 'TrendingUp',
    color: 'peach',
    difficulty: 'medium',
    instructions: [
      'Test your max squats on Day 1',
      'Follow the progressive plan: add 5-10 reps every 3 days',
      'Take rest days between sessions (every other day)',
      'Any squat variation counts (bodyweight, goblet, barbell)',
      'Final test on Day 30 — aim for 200 consecutive',
    ],
  },
  {
    id: 'challenge-5-workouts-week',
    name: '5 Workouts Per Week',
    description: 'Complete 5 workout sessions every week for 4 weeks. Build the ultimate training consistency.',
    type: ChallengeType.STREAK,
    targetValue: 20,
    unit: 'workouts',
    durationDays: 28,
    dailyTarget: undefined,
    pointsReward: 700,
    icon: 'Flame',
    color: 'red',
    difficulty: 'hard',
    instructions: [
      'Complete at least 5 workout sessions per week (Mon-Sun)',
      'Any workout type counts: strength, cardio, yoga, etc.',
      'Session must be at least 15 minutes to count',
      '2 rest/recovery days per week are built in',
      'Track your sessions in the workout diary',
    ],
  },
  {
    id: 'challenge-10000-calories',
    name: 'Burn 10,000 Calories',
    description: 'Burn a total of 10,000 calories through exercise in 30 days. That\'s ~333 per day.',
    type: ChallengeType.DURATION,
    targetValue: 10000,
    unit: 'kcal',
    durationDays: 30,
    dailyTarget: 333,
    pointsReward: 900,
    icon: 'Zap',
    color: 'red',
    difficulty: 'hard',
    instructions: [
      'Log all workout sessions to track calories burned',
      'Calories are estimated based on exercise type and duration',
      'Higher intensity workouts burn more calories',
      'Mix cardio and strength for best results',
      'Check your progress in the activity dashboard',
    ],
  },
  {
    id: 'challenge-core-month',
    name: 'Core Every Day',
    description: 'Do a dedicated core workout every single day for 14 days. Build an iron core.',
    type: ChallengeType.STREAK,
    targetValue: 14,
    unit: 'days',
    durationDays: 14,
    dailyTarget: 5, // at least 5 minutes of core work
    pointsReward: 400,
    icon: 'Hexagon',
    color: 'peach',
    difficulty: 'easy',
    instructions: [
      'Complete at least 5 minutes of core exercises daily',
      'Mix planks, crunches, leg raises, and rotational work',
      'Can be part of a larger workout or standalone',
      'Log the core work as a workout session',
      'Progress by increasing duration or difficulty',
    ],
  },
  {
    id: 'challenge-marathon-prep',
    name: 'Marathon Preparation',
    description: 'Run a total of 100km over 8 weeks as preparation for a marathon or half-marathon.',
    type: ChallengeType.DISTANCE,
    targetValue: 100,
    unit: 'km',
    durationDays: 56,
    dailyTarget: 1.8,
    pointsReward: 1000,
    icon: 'Award',
    color: 'blue',
    difficulty: 'hard',
    instructions: [
      'Accumulate 100km of running over 8 weeks',
      'That\'s roughly 12.5km per week on average',
      'Include one long run per week (progressive)',
      'Include easy runs and rest days',
      'Follow a structured plan if possible',
    ],
  },
];
