import type { Exercise } from '@/types/exercise';
import {
  ExerciseCategory,
  MuscleGroup,
  Difficulty,
} from '@/types/common';

/**
 * Complete exercise library — 82 exercises.
 * Each exercise includes MET values, instructions, tips, and muscle mappings.
 * All data is free, public-domain information based on exercise science.
 */
export const EXERCISES: Exercise[] = [
  // ============================================================
  // STRENGTH — CHEST
  // ============================================================
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 5.0,
    caloriesPerMinute: 5.8,
    description: 'The king of chest exercises. Lie flat on a bench, lower a barbell to your chest, then press it back up to full arm extension.',
    instructions: [
      'Lie flat on a bench with feet flat on the floor',
      'Grip the bar slightly wider than shoulder-width apart',
      'Unrack the bar and hold it directly over your chest with arms extended',
      'Lower the bar slowly to your mid-chest, keeping elbows at about 45 degrees',
      'Press the bar back up to the starting position by squeezing your chest',
      'Keep your shoulder blades retracted throughout the movement',
    ],
    tips: [
      'Do not bounce the bar off your chest',
      'Keep your feet flat for stability and leg drive',
      'Maintain a slight arch in your lower back',
      'Use a spotter for heavy sets',
    ],
    equipment: ['Barbell', 'Bench'],
    isBodyweight: false,
    imageKeyword: 'bench-press',
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 5.0,
    caloriesPerMinute: 5.8,
    description: 'Upper chest focused pressing movement performed on an inclined bench (30-45 degrees).',
    instructions: [
      'Set the bench to a 30-45 degree incline',
      'Lie back and grip the bar slightly wider than shoulder-width',
      'Unrack and hold the bar above your upper chest',
      'Lower the bar to your upper chest / collarbone area',
      'Press back up by squeezing your upper chest',
    ],
    tips: [
      'A 30-degree incline targets upper chest best',
      'Do not go too steep — it becomes a shoulder press',
      'Control the descent for 2-3 seconds',
    ],
    equipment: ['Barbell', 'Incline Bench'],
    isBodyweight: false,
    imageKeyword: 'incline-press',
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 4.0,
    caloriesPerMinute: 4.7,
    description: 'An isolation exercise that stretches and squeezes the chest muscles using a wide arcing motion with dumbbells.',
    instructions: [
      'Lie flat on a bench holding dumbbells above your chest',
      'Keep a slight bend in your elbows throughout',
      'Open your arms wide in an arc until you feel a stretch in your chest',
      'Squeeze your chest to bring the dumbbells back together',
      'Do not let your elbows drop below the bench level',
    ],
    tips: [
      'This is an isolation exercise — use lighter weight',
      'Focus on the stretch and squeeze, not the weight',
      'Keep the movement slow and controlled',
    ],
    equipment: ['Dumbbells', 'Bench'],
    isBodyweight: false,
    imageKeyword: 'dumbbell-fly',
  },
  {
    id: 'push-ups',
    name: 'Push-Ups',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS, MuscleGroup.CORE],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.8,
    caloriesPerMinute: 4.4,
    description: 'The fundamental bodyweight pushing exercise. Works chest, shoulders, triceps, and core simultaneously.',
    instructions: [
      'Start in a high plank position with hands slightly wider than shoulders',
      'Keep your body in a straight line from head to heels',
      'Lower your chest toward the floor by bending your elbows',
      'Push back up to the starting position by straightening your arms',
      'Keep your core engaged throughout',
    ],
    tips: [
      'Do not let your hips sag or pike up',
      'Full range of motion is key — go all the way down',
      'Modify by dropping to knees if needed',
      'Exhale on the push up, inhale on the way down',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'push-ups',
  },
  {
    id: 'chest-dip',
    name: 'Chest Dips',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.ADVANCED,
    metValue: 5.5,
    caloriesPerMinute: 6.4,
    description: 'Dips performed with a forward lean to emphasize the chest muscles over the triceps.',
    instructions: [
      'Grip parallel dip bars and hoist yourself up',
      'Lean your torso forward about 30-45 degrees',
      'Lower your body until your shoulders are slightly below your elbows',
      'Push back up to the starting position',
      'Keep your elbows flared out slightly to target chest',
    ],
    tips: [
      'The more you lean forward, the more chest involvement',
      'Do not lock out elbows at the top',
      'Control the negative portion of the movement',
    ],
    equipment: ['Dip Bars'],
    isBodyweight: false,
    imageKeyword: 'chest-dip',
  },
  {
    id: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 4.5,
    caloriesPerMinute: 5.3,
    description: 'A bench press variation with a narrow grip that shifts emphasis to the triceps.',
    instructions: [
      'Lie flat on a bench and grip the bar with hands shoulder-width apart',
      'Unrack and hold the bar over your lower chest',
      'Lower the bar to your lower chest while keeping elbows close to your body',
      'Press back up by extending your triceps',
    ],
    tips: [
      'Keep elbows tucked close to your sides',
      'Do not grip too narrow — shoulder-width is ideal',
      'Good for building triceps strength for bench press',
    ],
    equipment: ['Barbell', 'Bench'],
    isBodyweight: false,
    imageKeyword: 'close-grip-press',
  },

  // ============================================================
  // STRENGTH — BACK
  // ============================================================
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 5.0,
    caloriesPerMinute: 5.8,
    description: 'A compound back exercise that builds thickness and strength in the lats, rhomboids, and traps.',
    instructions: [
      'Stand with feet shoulder-width apart, hinge at the hips with knees slightly bent',
      'Grip the bar slightly wider than shoulder-width, overhand grip',
      'Pull the bar toward your lower chest / upper abdomen',
      'Squeeze your shoulder blades together at the top',
      'Lower the bar with control to full arm extension',
    ],
    tips: [
      'Keep your back flat — never round it',
      'Pull with your elbows, not your hands',
      'Your torso angle should stay consistent throughout',
    ],
    equipment: ['Barbell'],
    isBodyweight: false,
    imageKeyword: 'barbell-row',
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.BEGINNER,
    metValue: 4.5,
    caloriesPerMinute: 5.3,
    description: 'A unilateral back exercise performed one arm at a time, allowing for a full range of motion.',
    instructions: [
      'Place one knee and hand on a bench, other foot on the floor',
      'Hold a dumbbell in your free hand with arm hanging straight down',
      'Pull the dumbbell up to your hip/waist area by driving your elbow back',
      'Squeeze your back at the top for 1-2 seconds',
      'Lower with control to full extension',
    ],
    tips: [
      'Keep your back flat and parallel to the floor',
      'Pull your elbow toward your hip, not out to the side',
      'Do not rotate your torso to cheat the weight up',
    ],
    equipment: ['Dumbbell', 'Bench'],
    isBodyweight: false,
    imageKeyword: 'dumbbell-row',
  },
  {
    id: 'pull-down',
    name: 'Lat Pulldown',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.BEGINNER,
    metValue: 4.5,
    caloriesPerMinute: 5.3,
    description: 'A machine-based back exercise that mimics the pull-up motion, excellent for building lat width.',
    instructions: [
      'Sit at the pulldown machine and grip the bar wide with palms facing away',
      'Keep your torso upright or slightly leaned back',
      'Pull the bar down to your upper chest',
      'Squeeze your lats at the bottom',
      'Release the bar back up with control',
    ],
    tips: [
      'Do not lean too far back — it becomes a row',
      'Focus on pulling your elbows down toward your ribs',
      'Avoid using excessive momentum',
    ],
    equipment: ['Cable Machine'],
    isBodyweight: false,
    imageKeyword: 'pull-down',
  },
  {
    id: 'pull-ups',
    name: 'Pull-Ups',
    category: ExerciseCategory.CALISTHENICS,
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.ADVANCED,
    metValue: 8.0,
    caloriesPerMinute: 9.3,
    description: 'The ultimate upper body bodyweight exercise. Builds exceptional back and bicep strength.',
    instructions: [
      'Grip the pull-up bar slightly wider than shoulder-width, palms facing away',
      'Hang with arms fully extended (dead hang)',
      'Pull yourself up until your chin clears the bar',
      'Lower yourself with control back to dead hang',
    ],
    tips: [
      'Avoid kipping — use strict form',
      'If you cannot do one, use band assistance or negatives',
      'Focus on driving elbows down, not pulling with hands',
    ],
    equipment: ['Pull-Up Bar'],
    isBodyweight: true,
    imageKeyword: 'pull-ups',
  },
  {
    id: 'chin-ups',
    name: 'Chin-Ups',
    category: ExerciseCategory.CALISTHENICS,
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 8.0,
    caloriesPerMinute: 9.3,
    description: 'Similar to pull-ups but with an underhand grip, placing more emphasis on the biceps.',
    instructions: [
      'Grip the bar shoulder-width apart with palms facing toward you',
      'Hang from full extension',
      'Pull up until your chin is above the bar',
      'Lower with control',
    ],
    tips: [
      'The underhand grip makes this easier than pull-ups for most people',
      'Keep your core tight to minimize swinging',
      'Great for building both back and bicep strength',
    ],
    equipment: ['Pull-Up Bar'],
    isBodyweight: true,
    imageKeyword: 'chin-ups',
  },
  {
    id: 'cable-row',
    name: 'Seated Cable Row',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.BEGINNER,
    metValue: 4.0,
    caloriesPerMinute: 4.7,
    description: 'A machine-based rowing exercise that builds mid-back thickness with constant tension.',
    instructions: [
      'Sit at the cable row machine with feet on the platform',
      'Grip the handle with both hands',
      'Sit tall with a slight bend in knees',
      'Pull the handle to your abdomen while squeezing shoulder blades',
      'Return with control, keeping your back flat',
    ],
    tips: [
      'Do not round your back at any point',
      'Lean slightly forward at the start, sit upright at the finish',
      'Use a V-bar or close grip for more lat focus',
    ],
    equipment: ['Cable Machine'],
    isBodyweight: false,
    imageKeyword: 'cable-row',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.GLUTES, MuscleGroup.CORE],
    difficulty: Difficulty.ADVANCED,
    metValue: 6.0,
    caloriesPerMinute: 7.0,
    description: 'The king of compound lifts. Targets the entire posterior chain — back, glutes, hamstrings, and core.',
    instructions: [
      'Stand with feet hip-width apart, barbell over mid-foot',
      'Hinge at hips and grip the bar just outside your knees',
      'Drop your hips, lift your chest, and create tension in the bar',
      'Drive through your heels to stand up, keeping the bar close to your body',
      'Lock out by standing tall with hips extended',
      'Lower the bar back to the floor with control',
    ],
    tips: [
      'The bar must travel in a straight vertical line',
      'Your arms are just hooks — pull with your legs and back',
      'Never round your lower back under load',
      'Start light and master form before adding weight',
    ],
    equipment: ['Barbell'],
    isBodyweight: false,
    imageKeyword: 'deadlift',
  },
  {
    id: 'reverse-fly',
    name: 'Reverse Fly',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.BACK],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'An isolation exercise for the rear deltoids and upper back muscles.',
    instructions: [
      'Hold dumbbells and hinge forward at the hips',
      'Keep a slight bend in your elbows',
      'Raise the dumbbells out to the sides until parallel with the floor',
      'Squeeze your shoulder blades together at the top',
      'Lower with control',
    ],
    tips: [
      'Use light weights — this is a small muscle group',
      'Do not use momentum or swing',
      'Focus on the mind-muscle connection with rear delts',
    ],
    equipment: ['Dumbbells'],
    isBodyweight: false,
    imageKeyword: 'reverse-fly',
  },

  // ============================================================
  // STRENGTH — SHOULDERS
  // ============================================================
  {
    id: 'shoulder-press',
    name: 'Overhead Shoulder Press',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 4.5,
    caloriesPerMinute: 5.3,
    description: 'The primary compound movement for shoulder development. Can be done standing or seated with a barbell.',
    instructions: [
      'Start with the bar at collarbone height (use a rack)',
      'Grip the bar slightly wider than shoulder-width',
      'Press the bar overhead to full arm extension',
      'The bar should travel in a slight arc back over your head',
      'Lower back to the starting position with control',
    ],
    tips: [
      'Engage your core to prevent lower back arching',
      'Do not push your head forward — move your head back slightly to clear the bar',
      'Standing version engages more core; seated isolates shoulders more',
    ],
    equipment: ['Barbell'],
    isBodyweight: false,
    imageKeyword: 'shoulder-press',
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.5,
    caloriesPerMinute: 4.1,
    description: 'An isolation exercise specifically targeting the lateral (side) deltoid heads for shoulder width.',
    instructions: [
      'Stand holding dumbbells at your sides with a slight forward lean',
      'Raise the dumbbells out to the sides until shoulder height',
      'Lead with your elbows, not your hands',
      'Pause briefly at the top',
      'Lower with control back to the starting position',
    ],
    tips: [
      'Use lighter weights than you think — lateral delts are small',
      'Do not go above shoulder height to avoid impingement',
      'Keep a very slight bend in your elbows',
      'Avoid using momentum or shrugging',
    ],
    equipment: ['Dumbbells'],
    isBodyweight: false,
    imageKeyword: 'lateral-raise',
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'Isolates the anterior (front) deltoid heads using a forward raising motion.',
    instructions: [
      'Stand holding dumbbells in front of your thighs',
      'Raise one or both arms straight in front of you to shoulder height',
      'Keep your arm(s) straight with a very slight elbow bend',
      'Lower with control',
    ],
    tips: [
      'Alternate arms or raise both simultaneously',
      'Do not swing or use momentum',
      'Keep your torso still throughout',
    ],
    equipment: ['Dumbbells'],
    isBodyweight: false,
    imageKeyword: 'front-raise',
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.BACK],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'A cable exercise targeting rear delts and rotator cuff muscles, essential for shoulder health.',
    instructions: [
      'Set a cable with rope attachment to upper chest height',
      'Grip the rope ends and step back to create tension',
      'Pull the rope toward your face while spreading the rope ends apart',
      'Rotate your shoulders externally at the end position',
      'Return with control',
    ],
    tips: [
      'Excellent for shoulder health and posture correction',
      'Use moderate weight and focus on the squeeze',
      'Perform at the end of shoulder or back workouts',
    ],
    equipment: ['Cable Machine', 'Rope Attachment'],
    isBodyweight: false,
    imageKeyword: 'face-pull',
  },
  {
    id: 'shrug',
    name: 'Barbell Shrug',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.BACK],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'Targets the upper trapezius muscles for neck and shoulder development.',
    instructions: [
      'Stand holding a barbell at thigh level',
      'Keep arms straight and simply shrug your shoulders up toward your ears',
      'Hold the top position for 1-2 seconds',
      'Lower with control',
    ],
    tips: [
      'Do not roll your shoulders — shrug straight up and down',
      'Keep your head neutral, do not look up',
      'Can also be done with dumbbells',
    ],
    equipment: ['Barbell'],
    isBodyweight: false,
    imageKeyword: 'shrug',
  },

  // ============================================================
  // STRENGTH — ARMS (BICEPS)
  // ============================================================
  {
    id: 'bicep-curl',
    name: 'Barbell Bicep Curl',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARM],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'The classic bicep builder. A simple but effective isolation exercise for the biceps.',
    instructions: [
      'Stand holding a barbell at thigh level with an underhand grip',
      'Keep your elbows pinned to your sides',
      'Curl the weight up by contracting your biceps',
      'Squeeze at the top for 1 second',
      'Lower with control — do not drop the weight',
    ],
    tips: [
      'Do not swing your body to cheat the weight up',
      'Full range of motion is more important than heavy weight',
      'Keep your wrists straight throughout',
    ],
    equipment: ['Barbell'],
    isBodyweight: false,
    imageKeyword: 'bicep-curl',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARM],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'A bicep curl variation with a neutral grip that also targets the brachialis and forearm muscles.',
    instructions: [
      'Stand holding dumbbells at your sides with palms facing each other',
      'Curl one dumbbell up while keeping the neutral grip',
      'Squeeze at the top and lower with control',
      'Alternate arms or curl both simultaneously',
    ],
    tips: [
      'The neutral grip shifts emphasis to the brachialis',
      'Building the brachialis pushes the bicep up, making arms look bigger',
      'Keep elbows still at your sides',
    ],
    equipment: ['Dumbbells'],
    isBodyweight: false,
    imageKeyword: 'hammer-curl',
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'An isolation curl performed on a preacher bench, eliminating momentum and maximizing bicep stretch.',
    instructions: [
      'Sit at a preacher bench and place your arms over the pad',
      'Hold a barbell or EZ-bar with an underhand grip',
      'Curl the weight up to your chin',
      'Lower with control to full extension',
    ],
    tips: [
      'The pad prevents swinging — great for strict form',
      'Go slow on the negative for maximum muscle breakdown',
      'Do not fully extend at the bottom if it causes elbow pain',
    ],
    equipment: ['Preacher Bench', 'Barbell'],
    isBodyweight: false,
    imageKeyword: 'preacher-curl',
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 2.8,
    caloriesPerMinute: 3.3,
    description: 'A single-arm isolation curl performed seated, providing peak bicep contraction.',
    instructions: [
      'Sit on a bench with legs spread',
      'Hold a dumbbell in one hand, elbow resting on your inner thigh',
      'Curl the dumbbell up toward your shoulder',
      'Squeeze hard at the top for 1-2 seconds',
      'Lower with control',
    ],
    tips: [
      'Rotate your wrist slightly at the top for extra contraction',
      'Keep your elbow anchored to your thigh',
      'Best performed at the end of a bicep workout',
    ],
    equipment: ['Dumbbell', 'Bench'],
    isBodyweight: false,
    imageKeyword: 'concentration-curl',
  },

  // ============================================================
  // STRENGTH — ARMS (TRICEPS)
  // ============================================================
  {
    id: 'tricep-extension',
    name: 'Overhead Tricep Extension',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'An overhead tricep exercise using a dumbbell that targets the long head of the tricep.',
    instructions: [
      'Hold a dumbbell with both hands overhead',
      'Keep your elbows pointing forward and close together',
      'Lower the dumbbell behind your head by bending your elbows',
      'Extend your arms back to the starting position',
    ],
    tips: [
      'Keep your upper arms stationary — only your forearms move',
      'This is one of the best exercises for the long head',
      'Can also be done single-arm or with a cable',
    ],
    equipment: ['Dumbbell'],
    isBodyweight: false,
    imageKeyword: 'tricep-extension',
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'A cable machine isolation exercise for the triceps, emphasizing the lateral and medial heads.',
    instructions: [
      'Stand at a cable machine with rope or straight bar attachment at high setting',
      'Grip the attachment and tuck your elbows to your sides',
      'Push the weight down by extending your elbows',
      'Squeeze your triceps at full extension',
      'Release back up with control — do not let the weight snap back',
    ],
    tips: [
      'Keep your elbows pinned — do not let them flare',
      'Lean slightly forward for better angle',
      'Use a rope for more ROM, straight bar for heavier loads',
    ],
    equipment: ['Cable Machine'],
    isBodyweight: false,
    imageKeyword: 'tricep-pushdown',
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [MuscleGroup.CHEST],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 3.5,
    caloriesPerMinute: 4.1,
    description: 'A lying tricep extension where the bar is lowered toward the forehead or behind the head.',
    instructions: [
      'Lie on a bench holding an EZ-bar straight up over your chest',
      'Keep your elbows pointed up and stationary',
      'Lower the bar by bending your elbows toward your forehead or slightly behind',
      'Extend back to the starting position',
    ],
    tips: [
      'Use an EZ-bar to reduce wrist strain',
      'Do not let your elbows drift backward',
      'Keep the movement slow and controlled for safety',
    ],
    equipment: ['EZ-Bar', 'Bench'],
    isBodyweight: false,
    imageKeyword: 'skull-crusher',
  },
  {
    id: 'dips',
    name: 'Tricep Dips',
    category: ExerciseCategory.CALISTHENICS,
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 5.0,
    caloriesPerMinute: 5.8,
    description: 'Bodyweight dips performed with an upright torso to emphasize the triceps.',
    instructions: [
      'Grip parallel dip bars and hoist yourself up',
      'Keep your torso upright (do not lean forward)',
      'Lower your body by bending your elbows until they reach 90 degrees',
      'Push back up to full arm extension',
    ],
    tips: [
      'Upright posture = more triceps; leaning = more chest',
      'Do not go too deep to avoid shoulder strain',
      'Can add weight with a dip belt for progression',
    ],
    equipment: ['Dip Bars'],
    isBodyweight: true,
    imageKeyword: 'dips',
  },

  // ============================================================
  // STRENGTH — LEGS
  // ============================================================
  {
    id: 'squats',
    name: 'Barbell Back Squat',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 5.0,
    caloriesPerMinute: 5.8,
    description: 'The king of leg exercises. A full-body compound movement that builds massive leg and core strength.',
    instructions: [
      'Position the bar on your upper traps, grip it outside your shoulders',
      'Unrack and step back with feet shoulder-width apart',
      'Brace your core and unrack the bar',
      'Sit back and down by bending your hips and knees simultaneously',
      'Descend until your hips are at least parallel with your knees',
      'Drive through your heels to stand back up',
    ],
    tips: [
      'Keep your chest up and back flat throughout',
      'Push your knees out over your toes',
      'Depth is key — aim for at least parallel',
      'Warm up thoroughly before heavy sets',
    ],
    equipment: ['Barbell', 'Squat Rack'],
    isBodyweight: false,
    imageKeyword: 'squats',
  },
  {
    id: 'lunges',
    name: 'Walking Lunges',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES],
    difficulty: Difficulty.BEGINNER,
    metValue: 5.0,
    caloriesPerMinute: 5.8,
    description: 'A unilateral leg exercise that improves balance, coordination, and leg strength.',
    instructions: [
      'Stand tall with feet hip-width apart',
      'Take a large step forward with one leg',
      'Lower your body until both knees are at 90 degrees',
      'Push off your front foot and step forward into the next lunge',
      'Alternate legs as you walk',
    ],
    tips: [
      'Keep your torso upright throughout',
      'Do not let your front knee go too far past your toes',
      'Can be done with dumbbells for added resistance',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'lunges',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES],
    difficulty: Difficulty.BEGINNER,
    metValue: 4.5,
    caloriesPerMinute: 5.3,
    description: 'A machine-based compound leg exercise allowing heavy loading with lower back support.',
    instructions: [
      'Sit in the leg press machine with feet shoulder-width apart on the platform',
      'Unlock the safety handles and hold the side grips',
      'Lower the platform by bending your knees toward your chest',
      'Push the platform back up by extending your legs',
      'Do not lock out your knees at the top',
    ],
    tips: [
      'Hand placement affects foot positioning — experiment',
      'Higher feet = more glutes; lower feet = more quads',
      'Do not go so deep that your lower back rounds',
    ],
    equipment: ['Leg Press Machine'],
    isBodyweight: false,
    imageKeyword: 'leg-press',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.5,
    caloriesPerMinute: 4.1,
    description: 'An isolation exercise targeting the quadriceps muscles at the front of the thigh.',
    instructions: [
      'Sit on the leg extension machine with the pad against your lower shins',
      'Grip the side handles',
      'Extend your legs fully by straightening your knees',
      'Squeeze your quads at the top for 1 second',
      'Lower with control back to the starting position',
    ],
    tips: [
      'Good warm-up or finisher exercise for quads',
      'Do not use excessive weight — this is an isolation move',
      'Adjust the pad so it sits just above your ankles',
    ],
    equipment: ['Leg Extension Machine'],
    isBodyweight: false,
    imageKeyword: 'leg-extension',
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.5,
    caloriesPerMinute: 4.1,
    description: 'An isolation exercise targeting the hamstrings at the back of the thigh.',
    instructions: [
      'Lie face down on the leg curl machine with pads under your heels',
      'Grip the handles',
      'Curl the weight up by bending your knees',
      'Squeeze your hamstrings at the top',
      'Lower with control to full extension',
    ],
    tips: [
      'Can be done lying, seated, or standing — all target hamstrings',
      'Do not lift your hips off the pad',
      'Control the negative for maximum benefit',
    ],
    equipment: ['Leg Curl Machine'],
    isBodyweight: false,
    imageKeyword: 'leg-curl',
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'An isolation exercise for the calf muscles (gastrocnemius and soleus).',
    instructions: [
      'Stand on a raised surface with heels hanging off the edge',
      'Rise up onto your toes as high as possible',
      'Squeeze your calves at the top for 1-2 seconds',
      'Lower slowly past the platform level for a full stretch',
    ],
    tips: [
      'Calves respond well to high reps (15-25)',
      'Perform barefoot or in flat shoes for better range',
      'Pause at the bottom stretch for extra effectiveness',
    ],
    equipment: ['Calf Raise Machine'],
    isBodyweight: true,
    imageKeyword: 'calf-raise',
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.BACK],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 5.0,
    caloriesPerMinute: 5.8,
    description: 'A hip-hinge movement that targets the hamstrings and glutes with less spinal loading than conventional deadlifts.',
    instructions: [
      'Hold a barbell at thigh level with shoulder-width grip',
      'Keep your legs mostly straight with a slight knee bend',
      'Hinge at the hips, pushing your butt back',
      'Lower the bar along your legs until you feel a strong hamstring stretch',
      'Drive your hips forward to return to standing',
    ],
    tips: [
      'This is a hip hinge, not a squat — minimal knee bend',
      'Keep the bar close to your legs throughout',
      'You should feel this in your hamstrings, not your lower back',
    ],
    equipment: ['Barbell'],
    isBodyweight: false,
    imageKeyword: 'romanian-deadlift',
  },
  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.CORE],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 4.0,
    caloriesPerMinute: 4.7,
    description: 'The premier glute-building exercise. Involves thrusting hips upward while supported on a bench.',
    instructions: [
      'Sit on the floor with a bench behind you',
      'Roll a barbell over your hips and lean back against the bench',
      'Your upper back/shoulders should be on the bench',
      'Drive through your heels to thrust your hips up toward the ceiling',
      'Squeeze your glutes hard at the top',
      'Lower with control',
    ],
    tips: [
      'Place a pad around the bar for comfort',
      'Full lockout at the top with hips fully extended',
      'Do not hyperextend your lower back',
    ],
    equipment: ['Barbell', 'Bench'],
    isBodyweight: false,
    imageKeyword: 'hip-thrust',
  },
  {
    id: 'good-morning',
    name: 'Good Morning',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.BACK],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 4.0,
    caloriesPerMinute: 4.7,
    description: 'A hip-hinge exercise performed with a barbell on your back, targeting hamstrings and lower back.',
    instructions: [
      'Place a barbell on your upper back as if squatting',
      'Stand with feet shoulder-width apart, slight knee bend',
      'Hinge forward at the hips while keeping your back flat',
      'Lower your torso until parallel to the floor (or as far as flexibility allows)',
      'Drive your hips forward to return to standing',
    ],
    tips: [
      'Start with very light weight to learn the movement',
      'Keep the bar path close to your center of gravity',
      'If you feel this in your lower back, reduce the range of motion',
    ],
    equipment: ['Barbell'],
    isBodyweight: false,
    imageKeyword: 'good-morning',
  },

  // ============================================================
  // STRENGTH — CORE
  // ============================================================
  {
    id: 'plank',
    name: 'Plank',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.8,
    caloriesPerMinute: 4.4,
    description: 'An isometric core exercise that builds endurance in the abdominals, obliques, and lower back.',
    instructions: [
      'Start in a forearm plank position with elbows under your shoulders',
      'Your body should form a straight line from head to heels',
      'Engage your core by pulling your belly button toward your spine',
      'Hold the position for the target duration',
      'Breathe steadily throughout',
    ],
    tips: [
      'Do not let your hips sag or raise up',
      'If shaking, that means your core is working',
      'Start with 20-30 seconds and build up gradually',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'plank',
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.5,
    caloriesPerMinute: 4.1,
    description: 'A basic abdominal isolation exercise that flexes the spine to target the rectus abdominis.',
    instructions: [
      'Lie on your back with knees bent and feet flat on the floor',
      'Place your hands behind your head or crossed on your chest',
      'Contract your abs to lift your shoulders off the floor',
      'Do not sit all the way up — just lift the shoulder blades',
      'Lower with control',
    ],
    tips: [
      'Do not pull on your neck',
      'Focus on squeezing the abs, not just moving up and down',
      'Exhale on the way up, inhale on the way down',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'crunch',
  },
  {
    id: 'sit-up',
    name: 'Sit-Up',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.HIP_FLEXORS],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.8,
    caloriesPerMinute: 4.4,
    description: 'A full-range abdominal exercise where you sit up from a lying position.',
    instructions: [
      'Lie on your back with knees bent and feet anchored',
      'Cross your arms on your chest or place hands behind head',
      'Sit up fully until your torso is vertical',
      'Lower back down with control',
    ],
    tips: [
      'Anchoring your feet increases hip flexor involvement',
      'For pure abs, use crunches instead',
      'Control the descent — do not just drop back',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'sit-up',
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.5,
    caloriesPerMinute: 4.1,
    description: 'A rotational core exercise targeting the obliques and rectus abdominis.',
    instructions: [
      'Sit on the floor with knees bent and feet lifted (or anchored)',
      'Lean back slightly while keeping your back straight',
      'Hold your hands together in front of your chest',
      'Rotate your torso to one side, then the other',
      'Each side counts as one rep',
    ],
    tips: [
      'Keep your feet off the floor for added difficulty',
      'Can hold a weight or medicine ball for progression',
      'Rotate with your torso, not just your arms',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'russian-twist',
  },
  {
    id: 'leg-raise',
    name: 'Lying Leg Raise',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 3.5,
    caloriesPerMinute: 4.1,
    description: 'Targets the lower abdominals by raising the legs from a lying position.',
    instructions: [
      'Lie flat on your back with legs straight',
      'Place your hands under your hips or by your sides',
      'Keeping legs straight, raise them up to 90 degrees',
      'Slowly lower your legs back down without touching the floor',
    ],
    tips: [
      'Press your lower back into the floor throughout',
      'If straight legs are too hard, bend your knees slightly',
      'Do not use momentum — slow and controlled',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'leg-raise',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    category: ExerciseCategory.HIIT,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 8.0,
    caloriesPerMinute: 9.3,
    description: 'A dynamic plank variation that elevates the heart rate while intensely working the core.',
    instructions: [
      'Start in a high plank position',
      'Drive one knee toward your chest quickly',
      'As you return it, immediately drive the other knee forward',
      'Continue alternating at a brisk pace',
    ],
    tips: [
      'Keep your hips low — do not let them rise up',
      'The faster you go, the more cardiovascular the exercise',
      'Think of running in a plank position',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'mountain-climber',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: ExerciseCategory.CALISTHENICS,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.FOREARM],
    difficulty: Difficulty.ADVANCED,
    metValue: 5.0,
    caloriesPerMinute: 5.8,
    description: 'An advanced core exercise where you raise your legs while hanging from a pull-up bar.',
    instructions: [
      'Hang from a pull-up bar with an overhand grip',
      'Keeping legs straight, raise them up to hip height or higher',
      'Squeeze your abs at the top',
      'Lower with control — do not swing',
    ],
    tips: [
      'Avoid using momentum — this should be a strict movement',
      'If too hard, start with bent knees (knee raise)',
      'Grip strength may be a limiting factor initially',
    ],
    equipment: ['Pull-Up Bar'],
    isBodyweight: true,
    imageKeyword: 'hanging-leg-raise',
  },
  {
    id: 'commando-plank',
    name: 'Commando Plank',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.ARMS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 5.0,
    caloriesPerMinute: 5.8,
    description: 'A dynamic plank that transitions between forearm and hand positions, working the entire core.',
    instructions: [
      'Start in a high plank (push-up position)',
      'Lower down to your right forearm, then left forearm',
      'Push back up to your right hand, then left hand',
      'Continue alternating the lead arm each rep',
    ],
    tips: [
      'Keep your hips as still as possible',
      'Move one limb at a time — do not rush',
      'Alternate which arm leads to prevent imbalance',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'commando-plank',
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: ExerciseCategory.HIIT,
    primaryMuscles: [MuscleGroup.FULL_BODY],
    secondaryMuscles: [],
    difficulty: Difficulty.ADVANCED,
    metValue: 8.0,
    caloriesPerMinute: 9.3,
    description: 'The ultimate full-body conditioning exercise. Combines a squat, push-up, and jump into one explosive movement.',
    instructions: [
      'Stand with feet shoulder-width apart',
      'Drop into a squat and place your hands on the floor',
      'Kick your feet back into a plank position',
      'Perform a push-up',
      'Jump your feet back to your hands',
      'Explode up into a jump with arms overhead',
    ],
    tips: [
      'Scale by removing the push-up or jump as needed',
      'Focus on form over speed initially',
      'One of the best calorie-burning bodyweight exercises',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'burpee',
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.CORE, MuscleGroup.BACK],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 6.0,
    caloriesPerMinute: 7.0,
    description: 'An explosive hip-hinge movement using a kettlebell that builds power in the posterior chain.',
    instructions: [
      'Stand with feet wider than shoulder-width, kettlebell between your feet',
      'Hinge at hips to grip the kettlebell with both hands',
      'Hike the kettlebell back between your legs',
      'Explosively drive your hips forward to swing the kettlebell to chest height',
      'Let the kettlebell swing back down and repeat',
    ],
    tips: [
      'The power comes from your hips, not your arms',
      'Your arms are just pendulums — do not lift with them',
      'Keep your core braced and back flat',
    ],
    equipment: ['Kettlebell'],
    isBodyweight: false,
    imageKeyword: 'kettlebell-swing',
  },
  {
    id: 'turkish-get-up',
    name: 'Turkish Get-Up',
    category: ExerciseCategory.STRENGTH,
    primaryMuscles: [MuscleGroup.FULL_BODY],
    secondaryMuscles: [],
    difficulty: Difficulty.ADVANCED,
    metValue: 4.5,
    caloriesPerMinute: 5.3,
    description: 'A complex full-body exercise that involves moving from lying to standing while holding a weight overhead.',
    instructions: [
      'Lie on your back holding a kettlebell straight up with one arm',
      'Roll to your elbow, then to your hand',
      'Lift your hips into a bridge position',
      'Sweep your leg under into a lunge position',
      'Stand up while keeping the weight overhead',
      'Reverse the movements to return to lying',
    ],
    tips: [
      'Practice without weight first to learn the sequence',
      'Keep your eyes on the weight at all times',
      'Move slowly and deliberately — this is not a speed exercise',
    ],
    equipment: ['Kettlebell'],
    isBodyweight: false,
    imageKeyword: 'turkish-get-up',
  },

  // ============================================================
  // CARDIO
  // ============================================================
  {
    id: 'running-5mph',
    name: 'Running (5 mph / 12:00 pace)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.CORE],
    difficulty: Difficulty.BEGINNER,
    metValue: 8.3,
    caloriesPerMinute: 9.7,
    description: 'Light jogging pace suitable for beginners and recovery runs.',
    instructions: [
      'Start with a 5-minute walking warm-up',
      'Transition to a light jog at conversational pace',
      'Maintain an upright posture with slight forward lean',
      'Land with midfoot strike under your body',
      'Swing arms naturally at your sides',
    ],
    tips: [
      'You should be able to hold a conversation at this pace',
      'Focus on consistent breathing rhythm',
      'Stay hydrated before and after',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'running',
  },
  {
    id: 'running-6mph',
    name: 'Running (6 mph / 10:00 pace)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.CORE],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 9.8,
    caloriesPerMinute: 11.4,
    description: 'Moderate running pace — a common training speed for intermediate runners.',
    instructions: [
      'Warm up with 5 minutes of light jogging',
      'Settle into a steady pace at 10 minutes per mile',
      'Focus on efficient, relaxed running form',
      'Breathe rhythmically — try 3:2 inhale:exhale pattern',
    ],
    tips: [
      'This is a great aerobic training pace',
      'Most of your weekly miles should be near this pace',
      'Monitor your heart rate to stay in zone 2-3',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'running',
  },
  {
    id: 'running-7mph',
    name: 'Running (7 mph / 8:34 pace)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.CORE],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 11.0,
    caloriesPerMinute: 12.8,
    description: 'Tempo run pace — comfortably hard, used to build lactate threshold.',
    instructions: [
      'Warm up thoroughly before starting',
      'Run at a pace that feels "comfortably hard"',
      'You can speak in short phrases but not hold a conversation',
      'Maintain even effort, not necessarily even pace',
    ],
    tips: [
      'Tempo runs should be 20-40 minutes at this pace',
      'This pace improves your body\'s ability to clear lactate',
      'Do not do more than 1-2 tempo runs per week',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'running',
  },
  {
    id: 'running-8mph',
    name: 'Running (8 mph / 7:30 pace)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.CORE],
    difficulty: Difficulty.ADVANCED,
    metValue: 12.5,
    caloriesPerMinute: 14.6,
    description: 'Fast running pace used for interval training and speed work.',
    instructions: [
      'Requires thorough warm-up including strides',
      'Run at a pace that is hard but sustainable for the interval',
      'Focus on powerful arm swing and leg turnover',
      'Maintain relaxed shoulders and face',
    ],
    tips: [
      'Used for interval repeats (e.g., 400m-800m reps)',
      'Allow full recovery between intervals',
      'This is NOT a sustainable distance pace for most runners',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'running',
  },
  {
    id: 'running-10mph',
    name: 'Running (10 mph / 6:00 pace)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.CORE],
    difficulty: Difficulty.EXPERT,
    metValue: 14.5,
    caloriesPerMinute: 16.9,
    description: 'Near-sprint pace for advanced runners. 6-minute per mile pace.',
    instructions: [
      'Only attempt after building a strong running base',
      'Focus on maximal leg turnover and power output',
      'Run on a flat surface or track for safety',
      'Use for short intervals only (200-400m)',
    ],
    tips: [
      'This pace requires significant training background',
      'Always do extensive warm-up drills before sprints',
      'Recovery between reps should be 2-3x the work time',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'running',
  },
  {
    id: 'walking-3mph',
    name: 'Walking (3 mph)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 3.5,
    caloriesPerMinute: 4.1,
    description: 'Brisk walking at a moderate pace — the simplest form of cardio exercise.',
    instructions: [
      'Walk at a pace of about 20 minutes per mile',
      'Swing your arms naturally',
      'Maintain an upright posture',
      'Heel-to-toe walking pattern',
    ],
    tips: [
      'Great for recovery days or beginners',
      'Aim for 7000-10000 steps daily',
      'Easy to incorporate into daily routine',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'walking',
  },
  {
    id: 'cycling-moderate',
    name: 'Cycling (Moderate)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES],
    difficulty: Difficulty.BEGINNER,
    metValue: 8.0,
    caloriesPerMinute: 9.3,
    description: 'Moderate-intensity cycling on flat terrain or stationary bike at a steady pace.',
    instructions: [
      'Adjust seat height so leg is slightly bent at bottom of stroke',
      'Maintain a cadence of 70-90 RPM',
      'Keep your core engaged and upper body relaxed',
      'Pedal in smooth circles, not just pushing down',
    ],
    tips: [
      'Proper bike fit is essential to prevent injury',
      'Stay hydrated — cycling can dehydrate you quickly',
      'Use gears to maintain your target cadence on hills',
    ],
    equipment: ['Bicycle'],
    isBodyweight: false,
    imageKeyword: 'cycling',
  },
  {
    id: 'cycling-vigorous',
    name: 'Cycling (Vigorous)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    difficulty: Difficulty.ADVANCED,
    metValue: 10.0,
    caloriesPerMinute: 11.7,
    description: 'High-intensity cycling at 16-19 mph or heavy resistance on a stationary bike.',
    instructions: [
      'Warm up for 10 minutes at an easy pace',
      'Increase resistance or speed to reach vigorous intensity',
      'Maintain a cadence of 80-100 RPM',
      'Focus on even power delivery throughout the pedal stroke',
    ],
    tips: [
      'This intensity should feel hard — breathing heavily',
      'Great for building cardiovascular fitness and leg power',
      'Cool down for 5-10 minutes after',
    ],
    equipment: ['Bicycle'],
    isBodyweight: false,
    imageKeyword: 'cycling',
  },
  {
    id: 'jump-rope-fast',
    name: 'Jump Rope (Fast)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.CORE, MuscleGroup.SHOULDERS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 12.5,
    caloriesPerMinute: 14.6,
    description: 'Fast-paced jump roping — one of the most efficient calorie-burning exercises.',
    instructions: [
      'Hold handles at hip height with elbows close to body',
      'Rotate the rope with your wrists, not your arms',
      'Jump just high enough to clear the rope (1-2 inches)',
      'Stay on the balls of your feet',
      'Maintain a fast, consistent rhythm',
    ],
    tips: [
      'Start with short intervals (30 seconds) and build up',
      'Use a weighted rope for extra challenge',
      'Excellent for warming up or HIIT circuits',
    ],
    equipment: ['Jump Rope'],
    isBodyweight: true,
    imageKeyword: 'jump-rope',
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    difficulty: Difficulty.BEGINNER,
    metValue: 7.0,
    caloriesPerMinute: 8.2,
    description: 'A classic full-body cardio warm-up exercise that raises heart rate quickly.',
    instructions: [
      'Stand with feet together and arms at your sides',
      'Jump while spreading your legs wider than hip-width',
      'Simultaneously raise your arms overhead',
      'Jump again to return to starting position',
      'Maintain a steady rhythm',
    ],
    tips: [
      'Great for warming up before any workout',
      'Modify by stepping out instead of jumping if needed',
      'Keep your movements light and bouncy',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'jumping-jacks',
  },
  {
    id: 'rowing-machine-moderate',
    name: 'Rowing Machine (Moderate)',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.CORE, MuscleGroup.ARMS],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 7.0,
    caloriesPerMinute: 8.2,
    description: 'Full-body cardio on a rowing machine at a moderate, sustainable pace.',
    instructions: [
      'Sit on the seat with feet strapped in securely',
      'Start with arms extended, shins vertical (the catch)',
      'Drive with your legs first, then lean back, then pull with arms',
      'Reverse the motion: arms, body, legs (the recovery)',
      'Maintain a smooth, rhythmic stroke',
    ],
    tips: [
      'The legs do most of the work — do not pull with arms too early',
      'Aim for a stroke rate of 24-28 SPM for moderate intensity',
      'Keep your core engaged throughout',
    ],
    equipment: ['Rowing Machine'],
    isBodyweight: false,
    imageKeyword: 'rowing',
  },
  {
    id: 'stair-climbing',
    name: 'Stair Climbing',
    category: ExerciseCategory.CARDIO,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 9.0,
    caloriesPerMinute: 10.5,
    description: 'Climbing stairs or using a stair climber machine — excellent lower body cardio.',
    instructions: [
      'Step onto the stair climber or find a staircase',
      'Maintain an upright posture, do not lean on handrails',
      'Step fully onto each stair with your whole foot',
      'Maintain a steady climbing rhythm',
    ],
    tips: [
      'Incredible calorie burn — one of the best cardio exercises',
      'Builds leg strength while improving cardiovascular fitness',
      'Start slow and gradually increase speed or resistance',
    ],
    equipment: ['Stair Climber'],
    isBodyweight: false,
    imageKeyword: 'stair-climbing',
  },

  // ============================================================
  // HIIT
  // ============================================================
  {
    id: 'box-jumps',
    name: 'Box Jumps',
    category: ExerciseCategory.HIIT,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 8.0,
    caloriesPerMinute: 9.3,
    description: 'An explosive plyometric exercise where you jump onto an elevated surface.',
    instructions: [
      'Stand facing a sturdy box or platform',
      'Descend into a quarter squat and swing your arms back',
      'Explosively jump up onto the box, landing softly with both feet',
      'Stand up fully on the box',
      'Step down (do not jump down) and repeat',
    ],
    tips: [
      'Start with a lower box and progress higher',
      'Land softly — absorb the impact with your legs',
      'Never jump on an unstable surface',
    ],
    equipment: ['Plyo Box'],
    isBodyweight: true,
    imageKeyword: 'box-jumps',
  },
  {
    id: 'sprint-intervals',
    name: 'Sprint Intervals',
    category: ExerciseCategory.HIIT,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.CORE],
    difficulty: Difficulty.ADVANCED,
    metValue: 12.0,
    caloriesPerMinute: 14.0,
    description: 'Short, maximal-effort sprints alternated with rest or light jogging periods.',
    instructions: [
      'Warm up with 10 minutes of easy jogging',
      'Sprint at 85-95% maximum effort for the prescribed duration',
      'Recover with walking or light jogging',
      'Repeat for the prescribed number of rounds',
      'Cool down with 5 minutes of easy jogging',
    ],
    tips: [
      'Rest periods should be 2-3x the sprint duration',
      'Quality over quantity — each sprint should be maximal',
      'Do not attempt without a solid running base',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'sprinting',
  },

  // ============================================================
  // CALISTHENICS
  // ============================================================
  {
    id: 'pistol-squat',
    name: 'Pistol Squat',
    category: ExerciseCategory.CALISTHENICS,
    primaryMuscles: [MuscleGroup.LEGS],
    secondaryMuscles: [MuscleGroup.CORE, MuscleGroup.GLUTES],
    difficulty: Difficulty.EXPERT,
    metValue: 6.0,
    caloriesPerMinute: 7.0,
    description: 'A single-leg squat requiring exceptional strength, balance, and mobility.',
    instructions: [
      'Stand on one leg with the other leg extended in front',
      'Hold your arms out for balance',
      'Lower into a single-leg squat, keeping your extended leg off the floor',
      'Go as deep as your mobility allows',
      'Drive back up to standing on one leg',
    ],
    tips: [
      'One of the hardest bodyweight leg exercises',
      'Assisted variations: hold a pole, use a counterbalance',
      'Work on ankle and hip mobility first',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'pistol-squat',
  },
  {
    id: 'handstand',
    name: 'Handstand Hold',
    category: ExerciseCategory.CALISTHENICS,
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.CORE, MuscleGroup.TRICEPS],
    difficulty: Difficulty.ADVANCED,
    metValue: 2.8,
    caloriesPerMinute: 3.3,
    description: 'Holding a freestanding handstand — builds exceptional shoulder and core stability.',
    instructions: [
      'Place hands shoulder-width apart on the floor',
      'Kick up to a handstand position against a wall if needed',
      'Engage your core and push the ground away actively',
      'Hold the position with legs together and straight',
      'Look at your hands (not forward) to maintain balance',
    ],
    tips: [
      'Start with wall-assisted holds before attempting freestanding',
      'Finger strength is crucial for balance',
      'Build up hold time gradually (10 seconds at a time)',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'handstand',
  },
  {
    id: 'toes-to-bar',
    name: 'Toes to Bar',
    category: ExerciseCategory.CALISTHENICS,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.FOREARM],
    difficulty: Difficulty.ADVANCED,
    metValue: 6.0,
    caloriesPerMinute: 7.0,
    description: 'Hanging from a bar and swinging your toes up to touch it — an advanced core exercise.',
    instructions: [
      'Hang from a pull-up bar with an overhand grip',
      'Initiate a small kip swing for momentum',
      'Use your core to swing your toes up to touch the bar',
      'Control the swing back down',
    ],
    tips: [
      'Strict version (no kip) is much harder but better for pure core strength',
      'Common in CrossFit workouts',
      'Grip fatigue is often the limiting factor',
    ],
    equipment: ['Pull-Up Bar'],
    isBodyweight: true,
    imageKeyword: 'toes-to-bar',
  },
  {
    id: 'l-sit',
    name: 'L-Sit Hold',
    category: ExerciseCategory.CALISTHENICS,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.QUADRICEPS],
    difficulty: Difficulty.ADVANCED,
    metValue: 3.5,
    caloriesPerMinute: 4.1,
    description: 'Holding your body up with arms straight while legs are extended horizontally in an L shape.',
    instructions: [
      'Place hands on the floor or on parallettes beside your hips',
      'Press down to lift your body off the ground',
      'Extend your legs straight out in front of you',
      'Hold the position',
    ],
    tips: [
      'Start with tucked legs (tuck L-sit) to build strength',
      'Requires significant tricep and core strength',
      'Parallettes make this easier than the floor',
    ],
    equipment: ['Parallettes'],
    isBodyweight: true,
    imageKeyword: 'l-sit',
  },

  // ============================================================
  // FLEXIBILITY
  // ============================================================
  {
    id: 'yoga-hatha',
    name: 'Hatha Yoga',
    category: ExerciseCategory.FLEXIBILITY,
    primaryMuscles: [MuscleGroup.FULL_BODY],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 2.5,
    caloriesPerMinute: 2.9,
    description: 'A gentle form of yoga focusing on basic poses, breathing, and relaxation.',
    instructions: [
      'Begin in a comfortable seated position',
      'Move through basic poses: Mountain, Forward Fold, Warrior, Tree',
      'Hold each pose for 5-10 breaths',
      'Focus on steady breathing throughout',
      'End with a 5-minute savasana (relaxation)',
    ],
    tips: [
      'Never force a stretch — work within your comfort zone',
      'Consistency matters more than intensity',
      'Practice in a quiet, warm space for best results',
    ],
    equipment: ['Yoga Mat'],
    isBodyweight: true,
    imageKeyword: 'yoga',
  },
  {
    id: 'yoga-vinyasa',
    name: 'Vinyasa Yoga',
    category: ExerciseCategory.FLEXIBILITY,
    primaryMuscles: [MuscleGroup.FULL_BODY],
    secondaryMuscles: [MuscleGroup.CORE],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 4.0,
    caloriesPerMinute: 4.7,
    description: 'A dynamic, flowing style of yoga linking breath with movement through sequences of poses.',
    instructions: [
      'Begin with sun salutations to warm up',
      'Flow through sequences linking poses with breath',
      'Include standing, balancing, seated, and inverted poses',
      'Maintain ujjayi breathing throughout the practice',
    ],
    tips: [
      'More vigorous than Hatha — builds heat and stamina',
      'Each movement is paired with an inhale or exhale',
      'Great for building flexibility AND strength',
    ],
    equipment: ['Yoga Mat'],
    isBodyweight: true,
    imageKeyword: 'yoga',
  },
  {
    id: 'yoga-power',
    name: 'Power Yoga',
    category: ExerciseCategory.FLEXIBILITY,
    primaryMuscles: [MuscleGroup.FULL_BODY],
    secondaryMuscles: [MuscleGroup.CORE, MuscleGroup.LEGS],
    difficulty: Difficulty.ADVANCED,
    metValue: 5.5,
    caloriesPerMinute: 6.4,
    description: 'A fitness-based approach to Vinyasa yoga that builds strength, flexibility, and stamina.',
    instructions: [
      'Flow through challenging sequences with minimal rest',
      'Include strength-building poses: Chair, Warrior III, Crow',
      'Hold poses longer and add repetitions',
      'Maintain breath focus despite the intensity',
    ],
    tips: [
      'Bridges the gap between yoga and strength training',
      'Expect to sweat — this is a workout, not just stretching',
      'Not recommended for complete beginners',
    ],
    equipment: ['Yoga Mat'],
    isBodyweight: true,
    imageKeyword: 'yoga',
  },
  {
    id: 'stretching-general',
    name: 'Full Body Stretch',
    category: ExerciseCategory.FLEXIBILITY,
    primaryMuscles: [MuscleGroup.FULL_BODY],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 2.3,
    caloriesPerMinute: 2.7,
    description: 'A general full-body stretching routine targeting all major muscle groups.',
    instructions: [
      'Neck rolls and stretches',
      'Shoulder crosses and arm swings',
      'Cat-cow for spine mobility',
      'Standing quad stretch (each side 20-30 sec)',
      'Standing hamstring stretch (20-30 sec)',
      'Hip flexor stretch (each side 20-30 sec)',
      'Chest doorway stretch (20-30 sec)',
      'Seated butterfly stretch (30 sec)',
    ],
    tips: [
      'Hold each stretch for 20-30 seconds minimum',
      'Never bounce in a stretch — hold steady',
      'Stretch after workouts when muscles are warm',
      'Ideal as a cool-down routine',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'stretching',
  },
  {
    id: 'foam-rolling',
    name: 'Foam Rolling',
    category: ExerciseCategory.FLEXIBILITY,
    primaryMuscles: [MuscleGroup.FULL_BODY],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 2.5,
    caloriesPerMinute: 2.9,
    description: 'Self-myofascial release using a foam roller to reduce muscle tightness and improve recovery.',
    instructions: [
      'Roll slowly over each muscle group (1-2 minutes per area)',
      'Apply moderate pressure — it should be uncomfortable, not painful',
      'Pause on tender spots for 20-30 seconds',
      'Target: quads, hamstrings, IT band, calves, upper back, lats',
      'Avoid rolling directly on joints or bones',
    ],
    tips: [
      'Best done before or after workouts',
      'Consistency yields the best results',
      'Do not roll your lower back — only upper back',
    ],
    equipment: ['Foam Roller'],
    isBodyweight: false,
    imageKeyword: 'foam-rolling',
  },
  {
    id: 'pilates-mat',
    name: 'Mat Pilates',
    category: ExerciseCategory.FLEXIBILITY,
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.FULL_BODY],
    difficulty: Difficulty.INTERMEDIATE,
    metValue: 3.0,
    caloriesPerMinute: 3.5,
    description: 'Low-impact exercise focusing on core strength, posture, and flexibility through controlled movements.',
    instructions: [
      'Begin with breathing exercises and pelvic tilts',
      'Move through classic Pilates exercises: Hundred, Roll-Up, Single Leg Circles',
      'Focus on precision and control over speed',
      'Maintain core engagement throughout every movement',
      'End with spine stretches and relaxation',
    ],
    tips: [
      'Quality of movement is paramount in Pilates',
      'Breathe laterally — ribs expand to the sides',
      'Excellent for rehabilitation and posture correction',
    ],
    equipment: ['Yoga Mat'],
    isBodyweight: true,
    imageKeyword: 'pilates',
  },
  {
    id: 'mobility-work',
    name: 'Joint Mobility Routine',
    category: ExerciseCategory.FLEXIBILITY,
    primaryMuscles: [MuscleGroup.FULL_BODY],
    secondaryMuscles: [],
    difficulty: Difficulty.BEGINNER,
    metValue: 2.8,
    caloriesPerMinute: 3.3,
    description: 'Active range-of-motion exercises for all major joints to improve flexibility and prevent injury.',
    instructions: [
      'Neck circles (10 each direction)',
      'Shoulder circles forward and backward (10 each)',
      'Arm circles (10 each direction)',
      'Hip circles (10 each direction)',
      'Ankle circles (10 each direction)',
      'Wrist circles (10 each direction)',
      'Thoracic spine rotations (10 each side)',
      'World\'s Greatest Stretch (5 each side)',
    ],
    tips: [
      'Ideal as a warm-up before any workout',
      'Move slowly and deliberately through each circle',
      'Do not force any range of motion',
      'Can be done daily, even on rest days',
    ],
    equipment: [],
    isBodyweight: true,
    imageKeyword: 'mobility',
  },
];

/* ===== Quick Lookup Maps ===== */
export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e])
);

export const EXERCISES_BY_MUSCLE: Record<string, Exercise[]> = {};
for (const ex of EXERCISES) {
  for (const muscle of ex.primaryMuscles) {
    if (!EXERCISES_BY_MUSCLE[muscle]) EXERCISES_BY_MUSCLE[muscle] = [];
    EXERCISES_BY_MUSCLE[muscle].push(ex);
  }
}

export const EXERCISES_BY_CATEGORY: Record<string, Exercise[]> = {};
for (const ex of EXERCISES) {
  if (!EXERCISES_BY_CATEGORY[ex.category]) EXERCISES_BY_CATEGORY[ex.category] = [];
  EXERCISES_BY_CATEGORY[ex.category].push(ex);
}
